name: Create custom image

on:
  pull_request:
    branches:
      - main
    types: [closed]
      

env:
  PRODUCT_VERSION: "1.8.6" # or: "latest"
jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
    
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      
      - name: 'Go one directory up'
        run: cd ..

      - name: Zip webapp
        run: zip -r webapp.zip webapp
      
      - name: Setup HashiCorp Packer
        uses: hashicorp/setup-packer@v3.0.0
      
      - name: Initialize Packer template
        run: packer init packer/
        
      - name: Format Packer template
        run: packer fmt packer/
      
      - name: echo present working directory
        run: pwd

      - name: Validate Packer template
        env:
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          ACCOUNT_FILE: ${{ secrets.GCP_CREDENTIALS }}
        run: packer validate --var "mysql_password=$MYSQL_PASSWORD" --var "account_file_json_key=$ACCOUNT_FILE" packer/

      - name: Build the Packer
        env:
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          ACCOUNT_FILE: ${{ secrets.GCP_CREDENTIALS }}
        run: packer build --var "mysql_password=$MYSQL_PASSWORD" --var "account_file_json_key=$ACCOUNT_FILE"  packer/