name: format and validate packer

on:
    push: #change to pull_request later
        branches: 
            - A4 #change to main later

jobs:
    packer:
        runs-on: ubuntu-latest
        name: format-and-validate-packer
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Zip webapp
              run: zip -r webapp.zip webapp
            
            - name: Setup HashiCorp Packer
              uses: hashicorp/setup-packer@v3.0.0
        
            - name: Initialize Packer template
              run: packer init packer/

            - name: Validate Packer template
              run: packer validate packer/

            - name: Format Packer template
              run: packer fmt packer/