name: Create custom image

on:
  push:

jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
    
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Zip webapp
        run: zip -r webapp.zip .

      - name: cat pkr.hcl
        run: cat ./packer/*pkr.hcl
      - name: Build the Packer
        run: packer build -debug -var "mysql_password=${{ secrets.MYSQL_PASSWORD }}" ./packer/*pkr.hcl