name: format and validate packer

on:
    pull_request:
        branches: 
            - main

jobs:
    packer:
        runs-on: ubuntu-latest
        name: format-and-validate-packer
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Setup HashiCorp Packer
              uses: hashicorp/setup-packer@v3.0.0
            
            - name: Zip webapp
              run: zip -r webapp.zip .
        
            - name: Initialize Packer template
              run: packer init packer/

            - name: Format Packer template
              run: packer fmt packer/
      
            - name: Validate Packer template
              env:
                MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
                ACCOUNT_FILE: ${{ secrets.GCP_CREDENTIALS }}
              run: packer validate --var "mysql_password=$MYSQL_PASSWORD" --var "account_file_json_key=$ACCOUNT_FILE" packer/