name: Create custom image

on:
  pull_request: 
    types: [closed]
    branches: 
      - main

jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
    
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Zip webapp
        run: zip -r webapp.zip .

      - name: Build the Packer
        run: |
          packer build packer/*pkr.hcl \
            -var "port=${{ secrets.PORT }}" \
            -var "mysql_host=${{ secrets.MYSQL_HOST }}" \
            -var "mysql_user=${{ secrets.MYSQL_USER }}" \
            -var "mysql_password=${{ secrets.MYSQL_PASSWORD }}" \
            -var "mysql_database=${{ secrets.MYSQL_DATABASE }}" \
            -var "mysql_port=${{ secrets.MYSQL_PORT }}" \
            -var "mysql_root_password=${{ secrets.MYSQL_PASSWORD }}"