name: format and validate packer

on:
    pull_request: 
        branches: 
            - main

jobs:
    packer:
        runs-on: ubuntu-latest
        name: format-and-validate-packer
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: Setup HashiCorp Packer
              uses: hashicorp/setup-packer@v3.0.0
        

            - name: Validate Packer template
              run: packer validate packer/

            - name: Format Packer template
              run: packer fmt packer/