name: Integration Test

on:
  pull_request: 
    branches:
      - main

jobs:
    build:
      runs-on: ubuntu-latest
      name: Integration Tests
      steps:
        - uses: actions/checkout@v4
  
        - name: Set Up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20.4.0'
            
        - name: Install Dependencies
          run: npm install

        - name: Start MySQL
          run: | 
            sudo /etc/init.d/mysql start
        
  
        - name: Run Integration Tests
          run: npm test
          env:
            PORT: "8080"
            MYSQL_HOST: "localhost"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "root"
            MYSQL_DATABASE: "web_app_db"
            DIALECT: "mysql"
            MYSQL_PORT: "3306"
            NODE_ENV: 'test'
            JWT_SECRET: ${{ secrets.JWT_SECRET }}

            
            
      